### ISSUE TITLE
Fail to recognize file path with chinese characters

### ISSUE THREAD

**Issue by LeeTeng2001** [benchdoos/WeblocOpener#16] opened 2022-05-30 11:57 UTC
When I try to open a webloc link in a path that contains chinese characters it'll fail, the log output is as following:

2022-05-30 19:54:17,366 INFO c.g.b.w.u.Logging:61 [main] - Logging successfully started. Welcome to WeblocOpener v.1.11.1.333
2022-05-30 19:54:17,366 INFO c.g.b.w.u.s.SystemUtils:64 [main] - Initializing system...
2022-05-30 19:54:17,366 INFO c.g.b.w.u.s.SystemUtils:67 [main] - System: OS: Windows 8.1 6.3 x64 Processors: 20 JVM memory: 7232 MB (free:450 MB) Java v.1.8(1.8.0_51) runtime v.25.51-b03
2022-05-30 19:54:17,366 INFO c.g.b.w.c.Application:57 [main] - WeblocOpener starts in mode: WEBLOCOPENER
2022-05-30 19:54:17,366 INFO c.g.b.w.c.Application:58 [main] - WeblocOpener starts with arguments: [C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc]
2022-05-30 19:54:17,429 INFO c.g.b.w.c.Application:91 [main] - Got args: [C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc]
2022-05-30 19:54:17,429 INFO c.g.b.w.c.Application:349 [main] - Updates were checked less then 24h ago
2022-05-30 19:54:17,429 INFO c.g.b.w.s.DefaultAnalyzer:173 [main] - File [C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc] exists: false file?: false
2022-05-30 19:54:17,429 WARN c.g.b.w.s.DefaultAnalyzer:184 [main] - Wrong argument. Invalid file path or file not exist: C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc
2022-05-30 19:54:17,429 INFO c.g.b.w.s.DefaultAnalyzer:185 [main] - Trying to guess what file user wants to open
2022-05-30 19:54:17,429 INFO c.g.b.w.s.DefaultAnalyzer:187 [main] - Got files, that match: null
2022-05-30 19:54:17,429 WARN c.g.b.w.c.Application:171 [main] - Could not open file: C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc
java.io.FileNotFoundException: Can not analyze file: C:\Users\PC\OneDrive - sjtu.edu.cn\2021 ?? 2\CS2308 ??????\Algorithm and Complexity (2022) Website.webloc
	at com.github.benchdoos.weblocopener.service.DefaultAnalyzer.analyzeFile(DefaultAnalyzer.java:105) ~[WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.service.DefaultAnalyzer.<init>(DefaultAnalyzer.java:52) ~[WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.core.Application.runAnalyzer(Application.java:164) [WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.core.Application.manageArguments(Application.java:150) [WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.core.Application.manageSoloArgument(Application.java:355) [WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.core.Application.<init>(Application.java:67) [WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.Main.<init>(Main.java:46) [WeblocOpener.exe:?]
	at com.github.benchdoos.weblocopener.Main.main(Main.java:72) [WeblocOpener.exe:?]
2022-05-30 19:55:39,464 INFO c.g.b.w.u.Logging:61 [main] - Logging successfully started. Welcome to WeblocOpener v.1.11.1.333

As you can see,  the chinese character has been substituted with ????

**Comment by benchdoos** [comment] 2022-05-30 15:17
Can you provide some examples of path or filenames that app does not recognize?
Had a try to fix this issue and recent time hadn't find out how to do that(
This issue appears when cmd locale differs from unicode (and by default it does). You can see it on cmd-right click-preprties:

![image](https://user-images.githubusercontent.com/4706712/171021268-610b5010-bfca-4760-bbc9-eec19f7f919d.png)

**Comment by LeeTeng2001** [comment] 2022-05-31 00:53
The path I'm trying to open is: "C:\Users\PC\OneDrive - sjtu.edu.cn\2021 大二 2\CS2308 算法与复杂性\Algorithm and Complexity (2022) Website.webloc"

**Comment by LeeTeng2001** [comment] 2022-05-31 00:55
c

> Can you provide some examples of path or filenames that app does not recognize? Had a try to fix this issue and recent time hadn't find out how to do that( This issue appears when cmd locale differs from unicode (and by default it does). You can see it on cmd-right click-preprties:
> 
> ![image](https://user-images.githubusercontent.com/4706712/171021268-610b5010-bfca-4760-bbc9-eec19f7f919d.png)

I don't see this setting, I'm using Window 11

**Comment by benchdoos** [comment] 2022-05-31 16:04
> I don't see this setting, I'm using Window 11

Probably changed UI, didn't check this system yet.

> The path I'm trying to open is: "C:\Users\PC\OneDrive - sjtu.edu.cn\2021 大二 2\CS2308 算法与复杂性\Algorithm and Complexity (2022) Website.webloc"

Thanks for example, I'll try to reproduce and to fix it.

**Comment by benchdoos** [comment] 2022-06-03 19:53
Seems I've found solution. Will be fixed in `v2.0.0`

**Comment by benchdoos** [comment] 2023-02-08 16:13
After regress testing found out that bug still reproducible. 
Reason is launch4j wrapper: registered an issue - https://sourceforge.net/p/launch4j/bugs/229/
As an idea if it would not be fixed soon - create drag-and-drop window if file is not found to let user just drop it on the window and previous selected operation will be performed on all given files.
OR
turning back the file seeker that was working in previous versions of WeblocOpener to seek files through file system

Any of this solutions looks pretty bad... I guess next step is to look for another wrapper that has no such a problem

**Comment by benchdoos** [comment] 2023-02-08 16:18
OR
calling jar without wrapping through cmd in hidden mode... if it is possible
Anyway will find it out in v2.0.0-beta1

**Comment by benchdoos** [comment] 2023-03-02 20:11
WeblocOpener v2.0.0-beta.6 will have modernized algorithm to get file that was selected.
Launch4j gives no info about terms, so using algorithm until this problem will not be fixed.

**Comment by benchdoos** [comment] 2023-03-06 18:00
[WeblocOpener beta.6](https://github.com/benchdoos/WeblocOpener/releases/tag/v2.0.0.6) is available now.
@LeeTeng2001 can you test, if the problem is fixed?

**Comment by LeeTeng2001** [comment] 2023-03-07 01:23
ok I'll test today and let you know

**Comment by LeeTeng2001** [comment] 2023-03-07 05:21
Why do I need jdk 17? I ady have openjdk 19 insttalled but it's not being recognised?

**Comment by benchdoos** [comment] 2023-03-07 06:01
> Why do I need jdk 17? I ady have openjdk 19 insttalled but it's not being recognised?

You can use jdk 19 as well. But I’m not sure that openjdk didn’t cut off Java swing support. 
mat least I’ve tested openjdk 17 and they did…

**Comment by benchdoos** [comment] 2023-03-22 16:10
@LeeTeng2001 Sorry, did you have any problems with installing or launching WebloOpener on Java 19?

**Comment by LeeTeng2001** [comment] 2023-03-23 03:37
Hi, so far it's working fine !

**Comment by benchdoos** [comment] 2023-10-16 17:41
Hello, @LeeTeng2001! WeblocOpener 2 is available now! You can try it out, if the issue is not reproducing, I guess issue can be closed.
Otherwise will research if there are any updates in used libs

**Comment by benchdoos** [comment] 2023-11-05 20:51
Issue closed. Seems to be fixed. If the problems will appear again - create a new issue.

**Closed by benchdoos** 2023-11-05 20:51 UTC
Labels: bug, fixed
